name: バグ報告
description: 発生した問題の報告
title: "[BUG]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: dropdown
    id: server
    attributes:
      label: サーバー
      description: 問題が起きた時接続していたサーバー
      options:
        - Hub
        - サバイバル
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: client
    attributes:
      label: クライアントの種類
      description: 接続していた時に使用していたクライアント
      options:
        - 公式のバージョン
        - Forge
        - Fabric
        - 統合版
        - その他
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: バージョン
      description: 接続していた時に使用していたバージョン
      options:
        - 1.18
        - 1.17
        - 1.16
        - 1.15
        - 1.14
        - 1.13
        - 1.12
        - 1.11
        - 1.10
        - 1.9
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 発生した問題
      description: どのような問題が発生しましたか？
      placeholder: Tell us what you see!
      value: "バグが生じました!"
    validations:
      required: true
  - type: textarea
    id: Imitation
    attributes:
      label: 再現
      description: 問題を再現するための手順
      placeholder: Tell us what you see!
      value: "バグが生じました!"
    validations:
      required: false
  - type: input
    id: log
    attributes:
      label: クラッシュログ
      description: ログを張り付けてURLを共有してください。[Pastebin](https://pastebin.com/)
      placeholder: https://pastebin.com/AABBCC
    validations:
      required: false
  - type: checkboxes
    id: check
    attributes:
      label: 確認
      description: [Issue](https://github.com/mA0w0/mANetwork/issues) [Wiki](https://github.com/mA0w0/mANetwork/wiki) [Discord](https://discord.com)
      options:
        - 同じ問題が報告されてないことを確認しました。
        - Wikiを読みました。
        - Discordに参加しています。
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: 連絡先
      description: Disocrdのみです。
      placeholder: discord#0000
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        バグレポートにご協力いただきありがとうございます。
